version: "3.1"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/app
    depends_on:
      - php-fpm
    networks:
      - symfony_network

  php-fpm:
    container_name: php_fpm
    build: ./
    volumes:
      - ./app:/var/www/app
    networks:
      - symfony_network
    command: >
      sh -c "composer install && php-fpm -F"

networks:
  symfony_network:
    driver: bridge
